### ISSUE TITLE
Does not run out of the box

### ISSUE THREAD

**Issue by tvl83** [alleslabs/celatone-api#37]
Cloned repo, build image for docker. Tried to run the docker image and this is what I get

```
 docker run -p 8081:8080 celatone
[2023-10-19 15:04:59 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-10-19 15:04:59 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2023-10-19 15:04:59 +0000] [1] [INFO] Using worker: gthread
[2023-10-19 15:04:59 +0000] [7] [INFO] Booting worker with pid: 7
[2023-10-19 15:04:59 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.10/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/server/app.py", line 6, in <module>
    from routes import accounts, assets, cosmwasm, monitoring, icns, misc, registry, staking, transactions
  File "/app/server/routes/accounts.py", line 2, in <module>
    from adapters.aldus.accounts import AccountManager
  File "/app/server/adapters/aldus/accounts.py", line 2, in <module>
    from utils.aldus import get_aldus_chain_data
  File "/app/server/utils/aldus.py", line 3, in <module>
    from utils.constants import ALDUS_URL
  File "/app/server/utils/constants.py", line 3, in <module>
    PRICE_CACHER_URL = os.environ["PRICE_CACHER_URL"]
  File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'PRICE_CACHER_URL'
[2023-10-19 15:04:59 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-10-19 15:04:59 +0000] [1] [INFO] Shutting down: Master
[2023-10-19 15:04:59 +0000] [1] [INFO] Reason: Worker failed to boot.
```

There seems to be some environment variables required? `PRICE_CACHER_URL` ? 

Please advise. 

Thank you

**Comment by tansawit** [comment]
What are you looking to use the API for?

You don't need to run the API yourselves to be able to spin up Celatone frontend locally

**Comment by tvl83** [comment]
I was wanting to run it for another chain. Just running the front end can I configure a new chain? it's a cosmos chain, Migaloo

**Comment by tansawit** [comment]
Unfortunately no.

Celatone requires our custom indexer node to function. The API mainly serves as a proxy and to pull off chain data (asset prices, labels, etc).

That means running the API itself is not sufficient. And the API is also not currently meant to be run locally/by other teams.
